#include "toptions.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <nlohmann/json.hpp>
/*This code is generated by BinReadGenerator.cpp using classes stored in "toptions.h" file.
Do not change them!*/
void ReadFromBin(Coptions &obj, char *buf1,size_t BUF_SIZE)
{
	std::istringstream ifs(std::string(buf1, BUF_SIZE));
	char buf[500000];
	UShort_t len = 0;
	while(ifs)
	{
		ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
		ifs.read(reinterpret_cast<char*>(&buf), len);
		if(len<1){continue;}
		string str(buf, len - 1);
		if(str=="hS")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.hS), len);
		}
		else if(str=="Dt")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Dt), len);
		}
		else if(str=="Pre")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Pre), len);
		}
		else if(str=="Len")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Len), len);
		}
		else if(str=="hD")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.hD), len);
		}
		else if(str=="Trg")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Trg), len);
		}
		else if(str=="Drv")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Drv), len);
		}
		else if(str=="Thr")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Thr), len);
		}
		else if(str=="LT")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.LT), len);
		}
		else if(str=="G")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.G), len);
		}
		else if(str=="fdiv")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.fdiv), len);
		}
		else if(str=="AC")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.AC), len);
		}
		else if(str=="Inv")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Inv), len);
		}
		else if(str=="on")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.on), len);
		}
		else if(str=="pls")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.pls), len);
		}
		else if(str=="coinc_w")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.coinc_w), len);
		}
		else if(str=="mult_w1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.mult_w1), len);
		}
		else if(str=="mult_w2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.mult_w2), len);
		}
		else if(str=="group")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.group), len);
		}
		else if(str=="RD")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.RD), len);
		}
		else if(str=="RMask")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.RMask), len);
		}
		else if(str=="forcewr")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.forcewr), len);
		}
		else if(str=="Trigger")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Trigger), len);
		}
		else if(str=="Smpl")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Smpl), len);
		}
		else if(str=="St_Per")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.St_Per), len);
		}
		else if(str=="F24")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.F24), len);
		}
		else if(str=="DTW")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.DTW), len);
		}
		else if(str=="F_start")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.F_start), len);
		}
		else if(str=="F_stop")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.F_stop), len);
		}
		else if(str=="device")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.device), len);
		}
		else
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&buf), len);
		}
	}
}
void ReadFromBin(Toptions &obj, char *buf1,size_t BUF_SIZE)
{
	std::istringstream ifs(std::string(buf1, BUF_SIZE));
	char buf[500000];
	UShort_t len = 0;
	while(ifs)
	{
		ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
		ifs.read(reinterpret_cast<char*>(&buf), len);
		if(len<1){continue;}
		string str(buf, len - 1);
		if(str=="gitver")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.gitver), len);
		}
		else if(str=="ver_po")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ver_po), len);
		}
		else if(str=="maxch")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.maxch), len);
		}
		else if(str=="maxtp")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.maxtp), len);
		}
		else if(str=="chkall")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.chkall), len);
		}
		else if(str=="star")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.star), len);
		}
		else if(str=="chtype")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.chtype), len);
		}
		else if(str=="dsp")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.dsp), len);
		}
		else if(str=="Dsp")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Dsp), len);
		}
		else if(str=="Pls")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Pls), len);
		}
		else if(str=="St")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.St), len);
		}
		else if(str=="Ms")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Ms), len);
		}
		else if(str=="Grp")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Grp), len);
		}
		else if(str=="sS")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.sS), len);
		}
		else if(str=="sDrv")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.sDrv), len);
		}
		else if(str=="sThr")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.sThr), len);
		}
		else if(str=="sLT")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.sLT), len);
		}
		else if(str=="sD")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.sD), len);
		}
		else if(str=="B1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.B1), len);
		}
		else if(str=="B2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.B2), len);
		}
		else if(str=="P1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.P1), len);
		}
		else if(str=="P2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.P2), len);
		}
		else if(str=="dTm")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.dTm), len);
		}
		else if(str=="Pile")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Pile), len);
		}
		else if(str=="sTg")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.sTg), len);
		}
		else if(str=="DD")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.DD), len);
		}
		else if(str=="FF")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.FF), len);
		}
		else if(str=="T1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.T1), len);
		}
		else if(str=="T2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.T2), len);
		}
		else if(str=="W1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.W1), len);
		}
		else if(str=="W2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.W2), len);
		}
		else if(str=="Mt")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Mt), len);
		}
		else if(str=="Mr")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Mr), len);
		}
		else if(str=="Fpath")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Fpath), len);
		}
		else if(str=="calibr_t")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.calibr_t), len);
		}
		else if(str=="E0")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.E0), len);
		}
		else if(str=="E1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.E1), len);
		}
		else if(str=="E2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.E2), len);
		}
		else if(str=="Pz")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Pz), len);
		}
		else if(str=="E_auto")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.E_auto), len);
		}
		else if(str=="adj")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.adj), len);
		}
		else if(str=="elim1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.elim1), len);
		}
		else if(str=="elim2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.elim2), len);
		}
		else if(str=="T_acq")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.T_acq), len);
		}
		else if(str=="Period")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Period), len);
		}
		else if(str=="nthreads")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.nthreads), len);
		}
		else if(str=="Nchan")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Nchan), len);
		}
		else if(str=="Tstart")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Tstart), len);
		}
		else if(str=="Tstop")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Tstop), len);
		}
		else if(str=="tsleep")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.tsleep), len);
		}
		else if(str=="usb_size")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.usb_size), len);
		}
		else if(str=="rbuf_size")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.rbuf_size), len);
		}
		else if(str=="ibuf_size")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ibuf_size), len);
		}
		else if(str=="decbuf_size")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.decbuf_size), len);
		}
		else if(str=="rawbuf_size")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.rawbuf_size), len);
		}
		else if(str=="b_stack")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_stack), len);
		}
		else if(str=="b_norm")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_norm), len);
		}
		else if(str=="xdiv")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.xdiv), len);
		}
		else if(str=="ydiv")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ydiv), len);
		}
		else if(str=="icheck")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.icheck), len);
		}
		else if(str=="directraw")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.directraw), len);
		}
		else if(str=="checkdsp")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.checkdsp), len);
		}
		else if(str=="raw_write")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.raw_write), len);
		}
		else if(str=="fProc")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.fProc), len);
		}
		else if(str=="fTxt")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.fTxt), len);
		}
		else if(str=="fBin")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.fBin), len);
		}
		else if(str=="dec_write")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.dec_write), len);
		}
		else if(str=="root_write")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.root_write), len);
		}
		else if(str=="raw_compr")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.raw_compr), len);
		}
		else if(str=="dec_compr")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.dec_compr), len);
		}
		else if(str=="root_compr")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.root_compr), len);
		}
		else if(str=="dec_format")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.dec_format), len);
		}
		else if(str=="dec_mask")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.dec_mask), len);
		}
		else if(str=="Filename")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Filename), len);
		}
		else if(str=="Daqlog")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Daqlog), len);
		}
		else if(str=="Analog")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Analog), len);
		}
		else if(str=="Comment")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Comment), len);
		}
		else if(str=="addrandom")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.addrandom), len);
		}
		else if(str=="hideself")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.hideself), len);
		}
		else if(str=="wdog_timer")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.wdog_timer), len);
		}
		else if(str=="wdog1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.wdog1), len);
		}
		else if(str=="wdog2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.wdog2), len);
		}
		else if(str=="ch_name")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ch_name), len);
		}
		else if(str=="drawopt")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.drawopt), len);
		}
		else if(str=="ev_min")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ev_min), len);
		}
		else if(str=="ev_max")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ev_max), len);
		}
		else if(str=="buf_lag")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.buf_lag), len);
		}
		else if(str=="tgate")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.tgate), len);
		}
		else if(str=="tveto")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.tveto), len);
		}
		else if(str=="mult1")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.mult1), len);
		}
		else if(str=="mult2")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.mult2), len);
		}
		else if(str=="maintrig")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.maintrig), len);
		}
		else if(str=="seltab")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.seltab), len);
		}
		else if(str=="start_ch")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.start_ch), len);
		}
		else if(str=="ntof_period")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ntof_period), len);
		}
		else if(str=="TofZero")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.TofZero), len);
		}
		else if(str=="Prof_type")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof_type), len);
		}
		else if(str=="Ing_type")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Ing_type), len);
		}
		else if(str=="prof_nx")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.prof_nx), len);
		}
		else if(str=="prof_ny")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.prof_ny), len);
		}
		else if(str=="Ing_x")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Ing_x), len);
		}
		else if(str=="Ing_y")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Ing_y), len);
		}
		else if(str=="Prof_x")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof_x), len);
		}
		else if(str=="Prof_y")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof_y), len);
		}
		else if(str=="Prof64")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof64), len);
		}
		else if(str=="Prof64_TSP")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof64_TSP), len);
		}
		else if(str=="Prof64_W")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof64_W), len);
		}
		else if(str=="Prof64_THR")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof64_THR), len);
		}
		else if(str=="Prof64_GAT")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof64_GAT), len);
		}
		else if(str=="Prof64_X")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof64_X), len);
		}
		else if(str=="Prof64_Y")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Prof64_Y), len);
		}
		else if(str=="num_events")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.num_events), len);
		}
		else if(str=="num_buf")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.num_buf), len);
		}
		else if(str=="b_logy")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_logy), len);
		}
		else if(str=="b_stat")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_stat), len);
		}
		else if(str=="b_gcuts")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_gcuts), len);
		}
		else if(str=="b_roi")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_roi), len);
		}
		else if(str=="b_fpeaks")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_fpeaks), len);
		}
		else if(str=="b_deriv")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_deriv), len);
		}
		else if(str=="b_peak")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.b_peak), len);
		}
		else if(str=="adcm_period")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.adcm_period), len);
		}
		else if(str=="ncuts")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ncuts), len);
		}
		else if(str=="pcuts")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.pcuts), len);
		}
		else if(str=="gcut")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.gcut), len);
		}
		else if(str=="cut_form")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.cut_form), len);
		}
		else if(str=="formula")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.formula), len);
		}
		else if(str=="SimSim")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.SimSim), len);
		}
		else if(str=="Peak_thr")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Peak_thr), len);
		}
		else if(str=="Peak_wid")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Peak_wid), len);
		}
		else if(str=="Peak_bwidth")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Peak_bwidth), len);
		}
		else if(str=="Peak_maxpeaks")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Peak_maxpeaks), len);
		}
		else if(str=="Peak_smooth")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Peak_smooth), len);
		}
		else if(str=="Peak_show_sm")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Peak_show_sm), len);
		}
		else if(str=="Peak_use_mean")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Peak_use_mean), len);
		}
		else if(str=="Peak_print")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Peak_print), len);
		}
		else if(str=="OptPar")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.OptPar), len);
		}
		else if(str=="wrk_check")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.wrk_check), len);
		}
		else if(str=="Nrows")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.Nrows), len);
		}
		else if(str=="ScrollPos")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.ScrollPos), len);
		}
		else if(str=="hx_slider")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.hx_slider), len);
		}
		else if(str=="hy_slider")
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&obj.hy_slider), len);
		}
		else
		{
			ifs.read(reinterpret_cast<char*>(&len), sizeof(len));
			ifs.read(reinterpret_cast<char*>(&buf), len);
		}
	}
}
void ToJSON(Coptions &obj, nlohmann::json &jsn)
{
	jsn["Class"]="Coptions";
	vector<int> hS_vec;
	hS_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		hS_vec[i0]=obj.hS[i0];
	}
	jsn["hS"]=hS_vec;
	vector<int> Dt_vec;
	Dt_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Dt_vec[i0]=obj.Dt[i0];
	}
	jsn["Dt"]=Dt_vec;
	vector<int> Pre_vec;
	Pre_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Pre_vec[i0]=obj.Pre[i0];
	}
	jsn["Pre"]=Pre_vec;
	vector<int> Len_vec;
	Len_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Len_vec[i0]=obj.Len[i0];
	}
	jsn["Len"]=Len_vec;
	vector<int> hD_vec;
	hD_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		hD_vec[i0]=obj.hD[i0];
	}
	jsn["hD"]=hD_vec;
	vector<int> Trg_vec;
	Trg_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Trg_vec[i0]=obj.Trg[i0];
	}
	jsn["Trg"]=Trg_vec;
	vector<int> Drv_vec;
	Drv_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Drv_vec[i0]=obj.Drv[i0];
	}
	jsn["Drv"]=Drv_vec;
	vector<int> Thr_vec;
	Thr_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Thr_vec[i0]=obj.Thr[i0];
	}
	jsn["Thr"]=Thr_vec;
	vector<int> LT_vec;
	LT_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		LT_vec[i0]=obj.LT[i0];
	}
	jsn["LT"]=LT_vec;
	vector<int> G_vec;
	G_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		G_vec[i0]=obj.G[i0];
	}
	jsn["G"]=G_vec;
	vector<int> fdiv_vec;
	fdiv_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		fdiv_vec[i0]=obj.fdiv[i0];
	}
	jsn["fdiv"]=fdiv_vec;
	vector<bool> AC_vec;
	AC_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		AC_vec[i0]=obj.AC[i0];
	}
	jsn["AC"]=AC_vec;
	vector<bool> Inv_vec;
	Inv_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Inv_vec[i0]=obj.Inv[i0];
	}
	jsn["Inv"]=Inv_vec;
	vector<bool> on_vec;
	on_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		on_vec[i0]=obj.on[i0];
	}
	jsn["on"]=on_vec;
	vector<bool> pls_vec;
	pls_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		pls_vec[i0]=obj.pls[i0];
	}
	jsn["pls"]=pls_vec;
	vector<int> coinc_w_vec;
	coinc_w_vec.resize(2);
	for(int i0=0;i0<2;i0++)
	{
		coinc_w_vec[i0]=obj.coinc_w[i0];
	}
	jsn["coinc_w"]=coinc_w_vec;
	vector<int> mult_w1_vec;
	mult_w1_vec.resize(2);
	for(int i0=0;i0<2;i0++)
	{
		mult_w1_vec[i0]=obj.mult_w1[i0];
	}
	jsn["mult_w1"]=mult_w1_vec;
	vector<int> mult_w2_vec;
	mult_w2_vec.resize(2);
	for(int i0=0;i0<2;i0++)
	{
		mult_w2_vec[i0]=obj.mult_w2[i0];
	}
	jsn["mult_w2"]=mult_w2_vec;
	vector<vector<bool> > group_vec;
	group_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		group_vec[i0].resize(2);
		for(int i1=0;i1<2;i1++)
		{
			group_vec[i0][i1]=obj.group[i0][i1];
		}
	}
	jsn["group"]=group_vec;
	vector<int> RD_vec;
	RD_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		RD_vec[i0]=obj.RD[i0];
	}
	jsn["RD"]=RD_vec;
	jsn["RMask"]=obj.RMask;
	jsn["forcewr"]=obj.forcewr;
	jsn["Trigger"]=obj.Trigger;
	jsn["Smpl"]=obj.Smpl;
	jsn["St_Per"]=obj.St_Per;
	jsn["F24"]=obj.F24;
	vector<int> DTW_vec;
	DTW_vec.resize(2);
	for(int i0=0;i0<2;i0++)
	{
		DTW_vec[i0]=obj.DTW[i0];
	}
	jsn["DTW"]=DTW_vec;
	jsn["F_start"]=obj.F_start;
	jsn["F_stop"]=obj.F_stop;
}
void ToJSON(Toptions &obj, nlohmann::json &jsn)
{
	jsn["Class"]="Toptions";
	jsn["gitver"]=string(obj.gitver);
	jsn["maxch"]=obj.maxch;
	jsn["maxtp"]=obj.maxtp;
	jsn["chkall"]=obj.chkall;
	vector<bool> star_vec;
	star_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		star_vec[i0]=obj.star[i0];
	}
	jsn["star"]=star_vec;
	vector<int> chtype_vec;
	chtype_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		chtype_vec[i0]=obj.chtype[i0];
	}
	jsn["chtype"]=chtype_vec;
	vector<bool> dsp_vec;
	dsp_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		dsp_vec[i0]=obj.dsp[i0];
	}
	jsn["dsp"]=dsp_vec;
	vector<int> Dsp_vec;
	Dsp_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Dsp_vec[i0]=obj.Dsp[i0];
	}
	jsn["Dsp"]=Dsp_vec;
	vector<bool> Pls_vec;
	Pls_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Pls_vec[i0]=obj.Pls[i0];
	}
	jsn["Pls"]=Pls_vec;
	vector<bool> St_vec;
	St_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		St_vec[i0]=obj.St[i0];
	}
	jsn["St"]=St_vec;
	vector<bool> Ms_vec;
	Ms_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Ms_vec[i0]=obj.Ms[i0];
	}
	jsn["Ms"]=Ms_vec;
	vector<vector<bool> > Grp_vec;
	Grp_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Grp_vec[i0].resize(4);
		for(int i1=0;i1<4;i1++)
		{
			Grp_vec[i0][i1]=obj.Grp[i0][i1];
		}
	}
	jsn["Grp"]=Grp_vec;
	vector<int> sS_vec;
	sS_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		sS_vec[i0]=obj.sS[i0];
	}
	jsn["sS"]=sS_vec;
	vector<int> sDrv_vec;
	sDrv_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		sDrv_vec[i0]=obj.sDrv[i0];
	}
	jsn["sDrv"]=sDrv_vec;
	vector<int> sThr_vec;
	sThr_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		sThr_vec[i0]=obj.sThr[i0];
	}
	jsn["sThr"]=sThr_vec;
	vector<int> sLT_vec;
	sLT_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		sLT_vec[i0]=obj.sLT[i0];
	}
	jsn["sLT"]=sLT_vec;
	vector<float> sD_vec;
	sD_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		sD_vec[i0]=obj.sD[i0];
	}
	jsn["sD"]=sD_vec;
	vector<int> B1_vec;
	B1_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		B1_vec[i0]=obj.B1[i0];
	}
	jsn["B1"]=B1_vec;
	vector<int> B2_vec;
	B2_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		B2_vec[i0]=obj.B2[i0];
	}
	jsn["B2"]=B2_vec;
	vector<int> P1_vec;
	P1_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		P1_vec[i0]=obj.P1[i0];
	}
	jsn["P1"]=P1_vec;
	vector<int> P2_vec;
	P2_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		P2_vec[i0]=obj.P2[i0];
	}
	jsn["P2"]=P2_vec;
	vector<int> dTm_vec;
	dTm_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		dTm_vec[i0]=obj.dTm[i0];
	}
	jsn["dTm"]=dTm_vec;
	vector<int> Pile_vec;
	Pile_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Pile_vec[i0]=obj.Pile[i0];
	}
	jsn["Pile"]=Pile_vec;
	vector<int> sTg_vec;
	sTg_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		sTg_vec[i0]=obj.sTg[i0];
	}
	jsn["sTg"]=sTg_vec;
	vector<int> DD_vec;
	DD_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		DD_vec[i0]=obj.DD[i0];
	}
	jsn["DD"]=DD_vec;
	vector<int> FF_vec;
	FF_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		FF_vec[i0]=obj.FF[i0];
	}
	jsn["FF"]=FF_vec;
	vector<int> T1_vec;
	T1_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		T1_vec[i0]=obj.T1[i0];
	}
	jsn["T1"]=T1_vec;
	vector<int> T2_vec;
	T2_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		T2_vec[i0]=obj.T2[i0];
	}
	jsn["T2"]=T2_vec;
	vector<int> W1_vec;
	W1_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		W1_vec[i0]=obj.W1[i0];
	}
	jsn["W1"]=W1_vec;
	vector<int> W2_vec;
	W2_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		W2_vec[i0]=obj.W2[i0];
	}
	jsn["W2"]=W2_vec;
	vector<int> Mt_vec;
	Mt_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Mt_vec[i0]=obj.Mt[i0];
	}
	jsn["Mt"]=Mt_vec;
	vector<int> Mr_vec;
	Mr_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Mr_vec[i0]=obj.Mr[i0];
	}
	jsn["Mr"]=Mr_vec;
	vector<float> Fpath_vec;
	Fpath_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Fpath_vec[i0]=obj.Fpath[i0];
	}
	jsn["Fpath"]=Fpath_vec;
	vector<int> calibr_t_vec;
	calibr_t_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		calibr_t_vec[i0]=obj.calibr_t[i0];
	}
	jsn["calibr_t"]=calibr_t_vec;
	vector<float> E0_vec;
	E0_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		E0_vec[i0]=obj.E0[i0];
	}
	jsn["E0"]=E0_vec;
	vector<float> E1_vec;
	E1_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		E1_vec[i0]=obj.E1[i0];
	}
	jsn["E1"]=E1_vec;
	vector<float> E2_vec;
	E2_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		E2_vec[i0]=obj.E2[i0];
	}
	jsn["E2"]=E2_vec;
	vector<int> Pz_vec;
	Pz_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		Pz_vec[i0]=obj.Pz[i0];
	}
	jsn["Pz"]=Pz_vec;
	jsn["E_auto"]=obj.E_auto;
	vector<vector<float> > adj_vec;
	adj_vec.resize(261);
	for(int i0=0;i0<261;i0++)
	{
		adj_vec[i0].resize(3);
		for(int i1=0;i1<3;i1++)
		{
			adj_vec[i0][i1]=obj.adj[i0][i1];
		}
	}
	jsn["adj"]=adj_vec;
	vector<float> elim1_vec;
	elim1_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		elim1_vec[i0]=obj.elim1[i0];
	}
	jsn["elim1"]=elim1_vec;
	vector<float> elim2_vec;
	elim2_vec.resize(265);
	for(int i0=0;i0<265;i0++)
	{
		elim2_vec[i0]=obj.elim2[i0];
	}
	jsn["elim2"]=elim2_vec;
	jsn["T_acq"]=obj.T_acq;
	jsn["Period"]=obj.Period;
	jsn["nthreads"]=obj.nthreads;
	jsn["Nchan"]=obj.Nchan;
	jsn["Tstart"]=obj.Tstart;
	jsn["Tstop"]=obj.Tstop;
	jsn["tsleep"]=obj.tsleep;
	jsn["usb_size"]=obj.usb_size;
	jsn["rbuf_size"]=obj.rbuf_size;
	jsn["ibuf_size"]=obj.ibuf_size;
	jsn["decbuf_size"]=obj.decbuf_size;
	jsn["rawbuf_size"]=obj.rawbuf_size;
	jsn["b_stack"]=obj.b_stack;
	jsn["b_norm"]=obj.b_norm;
	jsn["xdiv"]=obj.xdiv;
	jsn["ydiv"]=obj.ydiv;
	jsn["icheck"]=obj.icheck;
	jsn["directraw"]=obj.directraw;
	jsn["checkdsp"]=obj.checkdsp;
	jsn["raw_write"]=obj.raw_write;
	jsn["fProc"]=obj.fProc;
	jsn["fTxt"]=obj.fTxt;
	jsn["fBin"]=obj.fBin;
	jsn["dec_write"]=obj.dec_write;
	jsn["root_write"]=obj.root_write;
	jsn["raw_compr"]=obj.raw_compr;
	jsn["dec_compr"]=obj.dec_compr;
	jsn["root_compr"]=obj.root_compr;
	jsn["dec_format"]=obj.dec_format;
	jsn["dec_mask"]=string(obj.dec_mask);
	jsn["Filename"]=string(obj.Filename);
	jsn["Daqlog"]=string(obj.Daqlog);
	jsn["Analog"]=string(obj.Analog);
	jsn["Comment"]=string(obj.Comment);
	jsn["addrandom"]=obj.addrandom;
	jsn["hideself"]=obj.hideself;
	jsn["wdog_timer"]=obj.wdog_timer;
	jsn["wdog1"]=obj.wdog1;
	jsn["wdog2"]=obj.wdog2;
	vector<string> ch_name_vec;
	ch_name_vec.resize(8);
	for(int i0=0;i0<8;i0++)
	{
		ch_name_vec[i0]=obj.ch_name[i0];
	}
	jsn["ch_name"]=ch_name_vec;
	jsn["drawopt"]=string(obj.drawopt);
	jsn["ev_min"]=obj.ev_min;
	jsn["ev_max"]=obj.ev_max;
	jsn["buf_lag"]=obj.buf_lag;
	jsn["tgate"]=obj.tgate;
	jsn["tveto"]=obj.tveto;
	jsn["mult1"]=obj.mult1;
	jsn["mult2"]=obj.mult2;
	jsn["maintrig"]=obj.maintrig;
	jsn["seltab"]=obj.seltab;
	jsn["start_ch"]=obj.start_ch;
	jsn["ntof_period"]=obj.ntof_period;
	jsn["TofZero"]=obj.TofZero;
	jsn["Prof_type"]=obj.Prof_type;
	jsn["Ing_type"]=obj.Ing_type;
	jsn["prof_nx"]=obj.prof_nx;
	jsn["prof_ny"]=obj.prof_ny;
	vector<int> Ing_x_vec;
	Ing_x_vec.resize(16);
	for(int i0=0;i0<16;i0++)
	{
		Ing_x_vec[i0]=obj.Ing_x[i0];
	}
	jsn["Ing_x"]=Ing_x_vec;
	vector<int> Ing_y_vec;
	Ing_y_vec.resize(16);
	for(int i0=0;i0<16;i0++)
	{
		Ing_y_vec[i0]=obj.Ing_y[i0];
	}
	jsn["Ing_y"]=Ing_y_vec;
	vector<int> Prof_x_vec;
	Prof_x_vec.resize(8);
	for(int i0=0;i0<8;i0++)
	{
		Prof_x_vec[i0]=obj.Prof_x[i0];
	}
	jsn["Prof_x"]=Prof_x_vec;
	vector<int> Prof_y_vec;
	Prof_y_vec.resize(8);
	for(int i0=0;i0<8;i0++)
	{
		Prof_y_vec[i0]=obj.Prof_y[i0];
	}
	jsn["Prof_y"]=Prof_y_vec;
	vector<int> Prof64_vec;
	Prof64_vec.resize(5);
	for(int i0=0;i0<5;i0++)
	{
		Prof64_vec[i0]=obj.Prof64[i0];
	}
	jsn["Prof64"]=Prof64_vec;
	jsn["Prof64_TSP"]=string(obj.Prof64_TSP);
	vector<int> Prof64_W_vec;
	Prof64_W_vec.resize(3);
	for(int i0=0;i0<3;i0++)
	{
		Prof64_W_vec[i0]=obj.Prof64_W[i0];
	}
	jsn["Prof64_W"]=Prof64_W_vec;
	jsn["Prof64_THR"]=obj.Prof64_THR;
	jsn["Prof64_GAT"]=obj.Prof64_GAT;
	jsn["Prof64_X"]=obj.Prof64_X;
	jsn["Prof64_Y"]=obj.Prof64_Y;
	jsn["num_events"]=obj.num_events;
	jsn["num_buf"]=obj.num_buf;
	jsn["b_logy"]=obj.b_logy;
	jsn["b_stat"]=obj.b_stat;
	jsn["b_gcuts"]=obj.b_gcuts;
	jsn["b_roi"]=obj.b_roi;
	jsn["b_fpeaks"]=obj.b_fpeaks;
	vector<bool> b_deriv_vec;
	b_deriv_vec.resize(5);
	for(int i0=0;i0<5;i0++)
	{
		b_deriv_vec[i0]=obj.b_deriv[i0];
	}
	jsn["b_deriv"]=b_deriv_vec;
	vector<bool> b_peak_vec;
	b_peak_vec.resize(14);
	for(int i0=0;i0<14;i0++)
	{
		b_peak_vec[i0]=obj.b_peak[i0];
	}
	jsn["b_peak"]=b_peak_vec;
	jsn["adcm_period"]=obj.adcm_period;
	jsn["ncuts"]=obj.ncuts;
	vector<int> pcuts_vec;
	pcuts_vec.resize(31);
	for(int i0=0;i0<31;i0++)
	{
		pcuts_vec[i0]=obj.pcuts[i0];
	}
	jsn["pcuts"]=pcuts_vec;
	vector<vector<vector<float> > > gcut_vec;
	gcut_vec.resize(31);
	for(int i0=0;i0<31;i0++)
	{
		gcut_vec[i0].resize(2);
		for(int i1=0;i1<2;i1++)
		{
			gcut_vec[i0][i1].resize(11);
			for(int i2=0;i2<11;i2++)
			{
				gcut_vec[i0][i1][i2]=obj.gcut[i0][i1][i2];
			}
		}
	}
	jsn["gcut"]=gcut_vec;
	vector<string> cut_form_vec;
	cut_form_vec.resize(31);
	for(int i0=0;i0<31;i0++)
	{
		cut_form_vec[i0]=obj.cut_form[i0];
	}
	jsn["cut_form"]=cut_form_vec;
	jsn["formula"]=string(obj.formula);
	vector<float> SimSim_vec;
	SimSim_vec.resize(20);
	for(int i0=0;i0<20;i0++)
	{
		SimSim_vec[i0]=obj.SimSim[i0];
	}
	jsn["SimSim"]=SimSim_vec;
	jsn["Peak_thr"]=obj.Peak_thr;
	jsn["Peak_wid"]=obj.Peak_wid;
	jsn["Peak_bwidth"]=obj.Peak_bwidth;
	jsn["Peak_maxpeaks"]=obj.Peak_maxpeaks;
	jsn["Peak_smooth"]=obj.Peak_smooth;
	jsn["Peak_show_sm"]=obj.Peak_show_sm;
	jsn["Peak_use_mean"]=obj.Peak_use_mean;
	jsn["Peak_print"]=obj.Peak_print;
	vector<vector<int> > OptPar_vec;
	OptPar_vec.resize(15);
	for(int i0=0;i0<15;i0++)
	{
		OptPar_vec[i0].resize(4);
		for(int i1=0;i1<4;i1++)
		{
			OptPar_vec[i0][i1]=obj.OptPar[i0][i1];
		}
	}
	jsn["OptPar"]=OptPar_vec;
	vector<int> wrk_check_vec;
	wrk_check_vec.resize(128);
	for(int i0=0;i0<128;i0++)
	{
		wrk_check_vec[i0]=obj.wrk_check[i0];
	}
	jsn["wrk_check"]=wrk_check_vec;
	jsn["Nrows"]=obj.Nrows;
	jsn["ScrollPos"]=obj.ScrollPos;
	vector<float> hx_slider_vec;
	hx_slider_vec.resize(2);
	for(int i0=0;i0<2;i0++)
	{
		hx_slider_vec[i0]=obj.hx_slider[i0];
	}
	jsn["hx_slider"]=hx_slider_vec;
	vector<float> hy_slider_vec;
	hy_slider_vec.resize(2);
	for(int i0=0;i0<2;i0++)
	{
		hy_slider_vec[i0]=obj.hy_slider[i0];
	}
	jsn["hy_slider"]=hy_slider_vec;
}
